import type { NextPage } from "next";
import Head from "next/head";
import { Player } from "../src/Components/Player";

export const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Radio testing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Player />
    </>
  );
};

export default Home;
